language: python
python:
- '3.5'
- '3.6'
install:
- pip install -U pip
- pip install pybuilder
- pip install -U pytest
- pip install -U coverage
- pyb install_dependencies
- pyb install
script:
- pyb run_unit_tests
after_script:
- pyb clean

before_deploy:
#need to switch to target directory for travis to find setup.py
- cd target/dist/RoboteQPy* 

deploy:
        provider: pypi
        user: gsisko
        password:
                secure: "f1AfXBNIelVgFMf0k5EnaGynopBgbAnVlhWBCxAjutxyY5pHl1iZircsNAbg4O/wlsc7Uz0TTuBlBdjSAgH7Mikys9VdUuhN5bAV1p60xhFeSMh+Td021kU2QhwFrKlghKLL5lO9umlqfISBPt9iW2g9cBfg1JIbg6spBUrKqgr711GhxB3R/xmmdUSd0KztAHCLBKjYH97Z/UqbrWejLxetEFfpRASB7sO4KK8ENrJh6Ivi1AAPzfXLj/p6q9zcA/Jk5/4b8V7Gap5Qa8JWzwbdHU/JvW63A5CIU16WQsfmBiGpDGT/OxsXiu15/LScj2tMpUN5mGcXBJ7vw5vFBpemdCimwOg0Q8jowHegRdzdYSWMn4L1xGAIXgPKKgiJgUTZ2o9UxWXofQ35zRAJC7rfnYf062egCPcVs5WlDauoqProGOdCDBm6qZBArYBr+HqPanRhEtbG2FYmrPrR0Hqajt3d3OX4vocYWJSniBC9sAZoY/cdG5X7Tr8J9hlAijdsowRpwj9C2fOJY/t4CIIM5ryWpIr811d4ZxHAXhMvEeauW+IwFkZNYTLZJs2aZK8HFlKHKH5EZvYtN+H330edyw5uSQzhP1ujniB95yo5zR9I7fPFHrZ8lpDgnb12jX61ZQoZC7na+eWRjZlZhAlVuPtWhVmur13D6YIyoIM="
        on:
                branch: master
        skip_existing: true
        skip_cleanup: true
     
