language: python
python:
        #Python 3.6
        - '3.5'
        - '3.6'
        #- '3.6-dev'  # 3.6 development branch

install:
        - pip install -U pip
        - pip install pybuilder
        - pip install -U pytest
        - pip install -U coverage
        - pyb install_dependencies
        - pyb install
script:
        - pyb run_unit_tests

after_script:
        - pyb clean
