language: python
python:
- '3.5'
- '3.6'
install:
- pip install -U pip
- pip install pybuilder
- pip install -U pytest
- pip install -U coverage
- pyb install_dependencies
- pyb install
script:
- pyb run_unit_tests
after_script:
- pyb clean

deploy:
        provider: pypi
        user: gsisko
        password:
                secure: YB+EF1dulzM4W/DWBkcn5EzLAA/a3pIZvnKf5TN9q0mKPO/APx5yNxUwlp7CDAm4aVyTxAxy4fJTxdhDeC7pgx8HqAg0SSCN7yysGe6Zcj3BeDECsGfFRizekAIqShNsaYmda94OrA35PWbmaADeZEN0ZtxK4s5YxL2DVV4CwtdlLvJvJQGizMmuW4MYBVa7eW+e16wVS2h3F3KS5uSeVdixKxmEUSfnQkIGloAgU/bVS9yjDR9lO3asLV8lP2niJ0p/dI2I+qzSTU0glikDbVgO+CKy/XAPTi4LNLEbiN5agjcpOi1Ma+IppzNCZb/BE0o+uG6CJH6tdLY1BgAEvGUpq/OFAoOKDhG9/4m11eRccwwUg4Cyw8lazj95ygA7CfekGPD4BUBhyEulIcKYMnS8TUQJ/5D2fxn2h9gFeBy36eRENHbCqQ5rSa/69sUZr42Yi37uQR1CXWuuwjPG8/4imNTUvGT8VMqA/PMCD1Ffrta+nTYOWzujvJXea5dGHKr2X2qSDpAVuT4RuEKUfK9RxMZARV28KLHo5H0aLPl8eRDYm1pFWUGJwJFl0qqoab8gFhnyqxsPU/7eFAk3e7ShtYdzyKjU+OH7XsHypRVCHqcioENNXzdXum4NWaeGQeZSjHzRxNktY+HJihoH21cUnhOfEdNl0l2Y+6OfGBE=
        on:
                branch: master
        skip_existing: true
     
