language: python
python:
- '3.5'
- '3.6'
install:
- pip install -U pip
- pip install pybuilder
- pip install -U pytest
- pip install -U coverage
- pyb install_dependencies
- pyb install
script:
- pyb run_unit_tests
after_script:
- pyb clean

before_deploy:
#need to switch to target directory for travis to find setup.py
- cd target/dist/RoboteQPy* 

deploy:
        provider: pypi
        user: gsisko
        password:
                secure: "UQn3PI4toogWgxfyZqybxeAdp4uqy1AnOiTPEP2wvVx6EsbfGzzn+fsZrubS2Kao31Bmhi3QiRvvZHGkfuQZ5epsEaiKxgWCz8LTZbwrHq0c+dZUGT65Q5gHleMGGWy7Dbk/Fv7vyB5234ozgxXJyWn3zA0lu2/Zi0+iHzH5DQxClihVteJCLR+gWl2e8KfnVVFrG7r9Fu9iZZBcXEVRkPQQE8j/yHQKQnsxZqTcta8yxR7rSWHUgYIFqesumPYoSiJpG+wL4aJpeJ01fDOGnkIZE7fN4/oEAaQYvK9C+jvuSJLLH85OYUeCp+m085dRwwSvn7Kh6xL0nRlZtg26AWapp/oji9VH6yyF5mJS8zLdtaskR6GgCx0GAMOiwz8sg0DJ3SbRJdnLwg8Doep48yWDk1nOKmCHoQcouxLz1UkgoxzhKe1u5LRx1LSeX9IsblmFTiwtu6kwUzu4Fo5vUUghJDJ0sMyJAbc+w42S15EJGl8P0f6+r61B5G9WbJyL5ybiKFshnIeU3lbiS3Ux/4EOb5LJvTDQiZ52tAFoix578qFZRCk+pStLJdxaFCiaPCXS2uNZe7cc/kBW/2/6o7I+oNimTsiFnDGQzx2JQRC2k2lUA/FaxGkVPhcgB5/9K/w4Z35X3Rn4LUTlbwAlQlrnmLvVGCyeU6jCjlyrB0c="
        on:
                branch: master
        skip_existing: true
        skip_cleanup: true
     
